openapi: 3.2.0
info:
  title: Lokki Password Recovery API
  description: The main API powering the Lokki Dashboard and Online Store
  version: '2.0'
  contact: {}
servers: []
security:
- x-access-token: []
tags:
- name: Password Recovery
paths:
  /v2/password-recovery/send-email:
    post:
      operationId: sendEmailPasswordRecovery
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitialPasswordRecoveryDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: boolean
      tags:
      - Password Recovery
  /v2/password-recovery/reset:
    post:
      operationId: resetPassword
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: boolean
      tags:
      - Password Recovery
components:
  schemas:
    ResetPasswordDto:
      type: object
      properties:
        token:
          type: string
        password:
          type: string
      required:
      - token
      - password
    InitialPasswordRecoveryDto:
      type: object
      properties:
        email:
          type: string
      required:
      - email
  securitySchemes:
    x-access-token:
      scheme: bearer
      bearerFormat: JWT
      type: apiKey
      in: header
      name: x-access-token
